### ISSUE TITLE
[non-timeline] Confusing undo behaviour

### ISSUE THREAD

**Issue by jrigg** [original-male/non#166]
_EDIT:_ Issue title changed from 'Region split error' after further investigation. See following posts.

################################################################################

When splitting a region at the playhead (shift+S) the new regions are sometimes duplicated in the same place with an accompanying 6dB level increase. Undoing only seems to undo one of the duplicated changes, leaving the others in a non-undoable state (or at least giving unpredictable undo behaviour).

Running non-timeline from the command line produces the following message when shift+S is used:
```
[non-timeline] ../timeline/src/Sequence.C:193 add(): Programming error: attempt to add sequence widget to the same sequence twice
```

**Comment by jrigg** [comment]
If it's useful I could email output from valgrind --leak-check=yes and valgrind --tool=helgrind (they're a bit large to post here).

**Comment by jrigg** [comment]
Further info: the error message described in the OP appears every time split is used. Sometimes duplicate regions are created, sometimes not. Undo history is messed up every time, eg. split region, create new track, drag one split region to new track, undo, and new track disappears along with the dragged region. The project is then unusable (refuses to connect to jackd next time it's opened) until the original track is removed.

**Comment by jrigg** [comment]
I've found one (the?) cause of the confusing behaviour. When a split is performed there are three actions: duplicate entire region, trim start of new region to split point, then trim end of original region to split point. 'Undo' only undoes the last one of those actions. This appears to happen with any operation which involves a set of actions - only the very last one is undone.

This appears to be the issue here (and the 'programming error' message is probably not significant).
I'll edit the title of the issue accordingly.

**Comment by original-male** [comment]
Yeah, those actions are supposed to be in an undo block together so they all get undone as a unit.

Just like when you select a bunch of regions and hit delete then undo, they should all come back together, not one at a time. Can you confirm that that kind of undo block is working it's just broken for the region splitting?

**Comment by jrigg** [comment]
After deleting multiple selected regions they all come back on 'Undo'.

**Comment by jrigg** [comment]
There's another confusing thing (which may be a separate issue): when dragging a region onto a new track at the same point in time the drag doesn't show up in the history file. Undo then removes the new track (along with the dragged region) instead of undoing the drag.

**Comment by original-male** [comment]
Are you doing this stuff on a new session or an existing one?

**Comment by jrigg** [comment]
I've been testing the split (and drag) behaviour on a new test session. I tested the multiple selection-delete-undo on a copy of an existing multitrack session.

**Comment by original-male** [comment]
@jrigg I've also pushed a fix for the problem you found when dragging a region from one track to another. If you have done this a lot in a session, then I recommend compacting it, as if the snapshot file is invalidated then the replaying of the history is likely to miss some of your region moves that weren't logged!

**Comment by jrigg** [comment]
Just did a git-pull and recompiled non-timeline.

1. The undo after split is still the same as before, ie. three separate undo operations are required to undo the split. Messages in xterm show only one of the three split actions is undoing with each Ctrl-Z or click on Edit->Undo (checking history file confirms this).

2. Dragging a region to another track now undoes correctly.

**Comment by original-male** [comment]
@jrigg How, exactly, are you performing the split? It matters. Splitting with the mouse always worked properly. Splitting with the 'S' key is what I fixed.

**Comment by jrigg** [comment]
Ah, I was splitting at the playhead using Shift-S. Undoing after splitting at the mouse pointer with the S key is indeed fixed.

**Comment by jrigg** [comment]
Something else has changed, possibly connected to the region drag fix: after using the region context menu the region 'sticks' to the mouse pointer and gets dragged around until the mouse is clicked on the background. This looks like a reversion to old behaviour that was fixed a little over a year ago (reported by me on mailing list May 2014). Given the choice between  no undo for region-drag-to-new-track  and this 'sticky' behaviour the former is easier to work with.

(BTW, apologies for discussing two separate problems in one issue report - I didn't realise they were unconnected when I opened the issue).

**Comment by original-male** [comment]
@jrigg Just pushed some more changes. Can you confirm that all issues mentioned in this thread are fixed?

**Comment by jrigg** [comment]
Confirmed. Thanks for fixing!

**Comment by original-male** [comment]
@jrigg Does this have and bearing on your need to have the fades in a different color?

**Comment by jrigg** [comment]
Only indirectly. I do a lot of small local gain changes when editing. In Ardour I used the envelope drawing tool, but in non-timeline I need to split regions, alter gain then drag region ends to set up overlaps for cross fades. Usually I drag alternate regions to another track, set overlaps and fades, then drag them back to the original track. Anything that helps visibility of fades makes this easier.

A more urgent reason was that I was switching to slightly lighter themes (normally I use Black Cairo) because the fade indication disappears at high zoom levels (Issue #164), so as a workaround I was looking at the overlap to estimate where to set fades. The lighter themes made it easier to see the overlap, but on lower zoom levels (where the fade indication was working) I then couldn't see the dark coloured fades very well.

That isn't as much of a problem here as the now-fixed Undo issue, as for very detailed gain changes I tend to edit the file in mhwaveedit or snd, save it as a new file and import it back into non-timeline.
